4.15. Адаптивная сетка
htmlacademy-adaptive/1777645-mishka-27 pull request #4
Opened 2022-12-19 17:01 UTC by FeHixX

2022-12-22 03:18 UTC, Dima-Dim requested changes
Есть ощущение что [zigzag-desktop.svg](https://github.com/htmlacademy-adaptive/1777645-mishka-27/pull/4/files#diff-2242be42abdbb4a46effd11078677ad137392e0608b3c4b747306f8da13e4efb) и [zigzag-tablet.svg](https://github.com/htmlacademy-adaptive/1777645-mishka-27/pull/4/files#diff-5c9a884ac39a2a8f016937d762df87bdd4edd732e334456e8bde7cb13e6a965e) это одно и тоже. Как и с другими подобными зигзагами.

2022-12-22 03:18 UTC, Dima-Dim commented on source/form.html
> +          <div class="request__text-wrapper">
Зачем оно тут? Почему сразу для p нельзя указать нужные стили?

2022-12-22 03:18 UTC, Dima-Dim commented on source/form.html
> +              <p class="request__heading request__heading--additionally">Доп</p>
Это и есть `label` да, какой-то непонятный. Но вот какой есть.

2022-12-22 03:18 UTC, Dima-Dim commented on source/sass/blocks/contacts.scss
> +      @media (min-width: variables.$width-desktop) {
Запутано получилось. Ниже же есть `@media (min-width: variables.$width-desktop)` , но в нём `&::after` как будто нет. По этому `&` и нужно использовать с осторожностью :)

2022-12-22 03:18 UTC, Dima-Dim commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Разбирай это в `.extra-list__item:first-child .extra-list__link {`

2022-12-22 03:18 UTC, Dima-Dim commented on source/sass/blocks/request.scss
>  }
Файл БЭМ блока в 460 строк это конечно перебор :) В отдельные блоки можно вынести стилизацию различных инпутов, например.

2022-12-22 03:18 UTC, Dima-Dim commented on source/sass/global/mixins.scss
> +@mixin visually-hidden {
Это просто отдельный блок, на самом деле.

2022-12-22 10:53 UTC, FeHixX commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Шапку переделал для 5 раздела, этого не будет. Почему такая запись не пригодна?

2022-12-22 11:11 UTC, Dima-Dim commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Во-первых потому что при следующем же редактировании сам в неё и запутаешься, во-вторых https://up.htmlacademy.ru/adaptive/27/criteries#d11

2022-12-22 11:42 UTC, FeHixX commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Все равно не понял, по критерию для :first-child мы должны использовать &, по другому я не знаю.

&:first-child {
  .extra-list__link {
  ...
  }

2022-12-22 11:49 UTC, FeHixX commented on source/form.html
> +              <p class="request__heading request__heading--additionally">Доп</p>
А можно делать доступность так:
<label class="request__heading request__heading--additionally>Доп<span class="visually-hidden">олнительное пожелание</span></p>

2022-12-22 12:21 UTC, Dima-Dim commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Не должны, а можем. А вот для `.extra-list__link` вообще не можем, а он уже за `&`, который был использован для предыдущей части селектора. И, как я написал выше, дело даже не в критерии, а в том, что это становится похоже на ребус, с которым не просто работать.

2022-12-22 12:29 UTC, FeHixX commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Т.е. для :first-child мы пишем:
```
.extra-list__item {
    &:first-child {
        стили
    }
```
а если нам надо скомбинировать селектор, мы пишем отдельно селектор:
```
.extra-list__item:first-child .extra-list__link {
    стили
}
```

2022-12-22 12:34 UTC, Dima-Dim commented on source/sass/blocks/extra-list.scss
> +    &:first-child .extra-list__link {
Критерий нам не запрещает написать :)
```
.extra-list__item {
    &:first-child {
        стили
    }
```

Да
```
.extra-list__item:first-child .extra-list__link {
    стили
}```
более удобный в плане чтения и дальнейшей поддержки вариант. Так же он удовлетворяет критериям.

2022-12-26 13:05 UTC, Dima-Dim commented on source/sass/blocks/request.scss
> +  &:hover .request__icon-input,
Нарушает https://up.htmlacademy.ru/adaptive/27/criteries#d11

2022-12-26 13:05 UTC, merged